---

driver_config:
    require_chef_omnibus: 11.12.2

provisioner:
  name: chef_zero
  data_bags_path: "../../data_bags"
  environments_path: "../../environments"
  roles_path: "../../roles"
  nodes_path: "../../nodes"

platforms:
  - name: ubuntu-local
    driver_plugin: vagrant
    driver_config:
      box: ubuntu_12_04_desktop
      box_url: "/Users/malcolm/dev/ubuntu-vm/box/virtualbox/ubuntu1204-desktop-chef11.12.4.box"

suites:
  - name: scarlett-server
    provisioner:
      client_rb:
        environment: "dev-scarlett"
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
        - ["forwarded_port", {guest: 22, host: 2200, auto_correct: true}]
        - ["private_network", {ip: "192.168.58.101"}]
      customize:
        natdnshostresolver1: "on"
        hostonlyadapter2: "vboxnet0"
        memory: 512
    run_list:
      - recipe[openssh::default]
      - recipe[bossjones-chef-scarlett::default]
      #- recipe[users::piusers]
      # attributes:
        # authorization:
          # sudo:
            # users: [ "pi" ]
